- SPORTRIP/src/main/java/stadium/StadiumMgr.java
- SPORTRIP/src/main/java/team/TeamMgr.java
> feat : add Mgr

- SPORTRIP/src/main/java/lodging/LodgingBean.java
- SPORTRIP/src/main/java/lodging/LodgingMgr.java
- SPORTRIP/src/main/java/reserve/ReserveBean.java
- SPORTRIP/src/main/java/reserve/ReserveMgr.java
- SPORTRIP/src/main/java/restaurant/RestaurantBean.java
- SPORTRIP/src/main/java/restaurant/RestaurantMgr.java
- SPORTRIP/src/main/java/room/RoomBean.java
- SPORTRIP/src/main/java/room/RoomMgr.java
객실, 예약, 숙박, 레스토랑 테이블 빈, mgr 추가
> room, reserve, lodging, restaurant 테이블 bean, mgr 추가

- SPORTRIP/src/main/java/board/BoardBean.java
- SPORTRIP/src/main/java/board/BoardMgr.java
> feat : add BoardMgr

- SPORTRIP/src/main/java/board/BoardMgr.java
- SPORTRIP/src/main/java/player/PlayerMgr.java
> feat : updatePlayerMgr

- SPORTRIP/src/main/java/basket/BasketBean.java
- SPORTRIP/src/main/java/basket/BasketMgr.java
- SPORTRIP/src/main/java/board/BoardMgr.java
- SPORTRIP/src/main/java/charge/ChargeBean.java
- SPORTRIP/src/main/java/charge/ChargeMgr.java
- SPORTRIP/src/main/java/md/MDBean.java
- SPORTRIP/src/main/java/md/MDMgr.java
- SPORTRIP/src/main/java/player/PlayerBean.java
- SPORTRIP/src/main/java/player/PlayerMgr.java
- SPORTRIP/src/main/java/user/UserMgr.java
> fix : update Mgr

- SPORTRIP/src/main/java/lodging/LodgingBean.java
- SPORTRIP/src/main/java/lodging/LodgingMgr.java
- SPORTRIP/src/main/java/reserve/ReserveBean.java
- SPORTRIP/src/main/java/reserve/ReserveMgr.java
- SPORTRIP/src/main/java/restaurant/RestaurantBean.java
- SPORTRIP/src/main/java/restaurant/RestaurantMgr.java
- SPORTRIP/src/main/java/room/RoomBean.java
- SPORTRIP/src/main/java/room/RoomMgr.java
lodging, reserve, restaurant, room bean 및 mgr 수정
> lodging, reserve, restaurant, room bean 및 mgr 수정

- SPORTRIP/src/main/java/team/TeamMgr.java
- SPORTRIP/src/main/webapp/UI/soccer_main.html
- SPORTRIP/src/main/webapp/UI/soccer_teamRank.jsp
> soccer teamrank DBlink

- SPORTRIP/src/main/webapp/UI/sport/main_highlight.jsp
- SPORTRIP/src/main/webapp/UI/sport/soccer_teamRank.jsp
- SPORTRIP/src/main/webapp/UI/sport/sport_main.jsp
> 하이라이트, 순위 간 페이지 동적 연결

- SPORTRIP/src/main/webapp/UI/assets/css/style.css
- SPORTRIP/src/main/webapp/UI/team/teamPage_Player.jsp
- SPORTRIP/src/main/webapp/UI/team/teamPage_Stadium.jsp
> 경기장 사진 경로 수정

- SPORTRIP/src/main/java/user/UserBean.java
- SPORTRIP/src/main/java/user/UserMgr.java
- SPORTRIP/src/main/webapp/UI/team/team_header.jsp
- SPORTRIP/src/main/webapp/UI/user/signup.jsp
- SPORTRIP/src/main/webapp/UI/user/signupCheck.jsp
- SPORTRIP/src/main/webapp/UI/user/validateId.jsp
> feat : add SignIn

- SPORTRIP/src/main/java/DB/MUtil.java
- SPORTRIP/src/main/java/user/UserMgr.java
- SPORTRIP/src/main/webapp/UI/sport/mainPage.jsp
- SPORTRIP/src/main/webapp/UI/sport/main_highlight.jsp
- SPORTRIP/src/main/webapp/UI/sport/sport_header.jsp
- SPORTRIP/src/main/webapp/UI/sport/sport_main.jsp
- SPORTRIP/src/main/webapp/UI/sport/sport_matchDate.jsp
- SPORTRIP/src/main/webapp/UI/sport/team_rank.jsp
- SPORTRIP/src/main/webapp/UI/team/teamPage_Player.jsp
- SPORTRIP/src/main/webapp/UI/user/login.jsp
- SPORTRIP/src/main/webapp/UI/user/loginCheck.jsp
> update login & header

- SPORTRIP/.settings/org.eclipse.core.resources.prefs
- SPORTRIP/src/main/webapp/UI/sport/main_highlight.jsp
- SPORTRIP/src/main/webapp/UI/team/teamPage_Player.jsp
- SPORTRIP/src/main/webapp/UI/team/teamPage_highlight.jsp
> feat : add team_highlight

- SPORTRIP/src/main/webapp/UI/user/login.jsp
> fix : update login

- SPORTRIP/src/main/webapp/UI/admin/admin_addPlayer.jsp
- SPORTRIP/src/main/webapp/UI/admin/insert_player.jsp
> feat : addplayer

- SPORTRIP/src/main/java/player/PlayerMgr.java
- SPORTRIP/src/main/webapp/UI/admin/admin_player.jsp
- SPORTRIP/src/main/webapp/UI/admin/admin_updatePlayer.jsp
- SPORTRIP/src/main/webapp/UI/admin/updatePlayer.jsp
> feat : playerUpdate

- SPORTRIP/src/main/webapp/UI/board/board_post.jsp
- SPORTRIP/src/main/webapp/UI/board/comments.jsp
- SPORTRIP/src/main/webapp/UI/board/viewPost.jsp
- SPORTRIP/src/main/webapp/UI/team/teamPage_board.jsp
> comments 수정

- SPORTRIP/src/main/java/matchdate/MatchdateBean.java
- SPORTRIP/src/main/java/matchdate/MatchdateMgr.java
- SPORTRIP/src/main/webapp/UI/sport/sport_matchDate.jsp
> fix:update matcheDate

- SPORTRIP/src/main/webapp/UI/board/board_command.jsp
- SPORTRIP/src/main/webapp/UI/board/board_delete.jsp
- SPORTRIP/src/main/webapp/UI/board/board_in.jsp
- SPORTRIP/src/main/webapp/UI/board/comment_in.jsp
- SPORTRIP/src/main/webapp/UI/board/comment_re.jsp
- SPORTRIP/src/main/webapp/UI/board/comment_update.jsp
- SPORTRIP/src/main/webapp/UI/board/viewPost.jsp
> board delete update

- SPORTRIP/src/main/java/board/BoardMgr.java
- SPORTRIP/src/main/webapp/UI/board/board_post.jsp
- SPORTRIP/src/main/webapp/UI/board/board_post_in.jsp
- SPORTRIP/src/main/webapp/UI/board/board_update.jsp
- SPORTRIP/src/main/webapp/UI/board/board_update_in.jsp
- SPORTRIP/src/main/webapp/UI/board/viewPost.jsp
> board update 수정

- SPORTRIP/src/main/webapp/UI/admin/admin_board.jsp
- SPORTRIP/src/main/webapp/UI/admin/admin_goods.jsp
- SPORTRIP/src/main/webapp/UI/admin/admin_header.jsp
- SPORTRIP/src/main/webapp/UI/admin/admin_player.jsp
- SPORTRIP/src/main/webapp/UI/team/teamPage_board.jsp
> admin_header

- SPORTRIP/src/main/webapp/UI/sport/sport_main.jsp
- SPORTRIP/src/main/webapp/UI/team/teamPage_highlight.jsp
> fix : teamPage_highLight

- SPORTRIP/src/main/webapp/UI/admin/admin_addBoard.jsp
- SPORTRIP/src/main/webapp/UI/admin/admin_board.jsp
- SPORTRIP/src/main/webapp/UI/admin/admin_goods.jsp
- SPORTRIP/src/main/webapp/UI/admin/admin_header.jsp
- SPORTRIP/src/main/webapp/UI/admin/admin_player.jsp
- SPORTRIP/src/main/webapp/UI/md/shoppingPage_basket.jsp
- SPORTRIP/src/main/webapp/UI/team/teamPage_board.jsp
- SPORTRIP/src/main/webapp/UI/team/teamPage_highlight.jsp
- SPORTRIP/src/main/webapp/UI/team/teamPage_player.jsp
- SPORTRIP/src/main/webapp/UI/team/teamPage_stadium.jsp
- SPORTRIP/src/main/webapp/UI/team/teamPage_store.jsp
- SPORTRIP/src/main/webapp/UI/team/teamPage_teamintro.jsp
- SPORTRIP/src/main/webapp/UI/team/team_header.jsp
> header_update

- SPORTRIP/src/main/java/basket/BasketMgr.java
- SPORTRIP/src/main/java/charge/ChargeMgr.java
- SPORTRIP/src/main/java/lodging/LodgingMgr.java
- SPORTRIP/src/main/java/reserve/ReserveMgr.java
- SPORTRIP/src/main/java/restaurant/RestaurantMgr.java
- SPORTRIP/src/main/java/room/RoomMgr.java
- SPORTRIP/src/main/java/user/UserMgr.java
- SPORTRIP/src/main/webapp/UI/md/delete_payment.jsp
- SPORTRIP/src/main/webapp/UI/md/saveCharge.jsp
- SPORTRIP/src/main/webapp/UI/md/shoppingPage_basket.jsp
- SPORTRIP/src/main/webapp/UI/md/shoppingPage_payment.jsp
- SPORTRIP/src/main/webapp/UI/md/shoppingPage_paymentDetail.jsp
> feat : paymentDetail

- SPORTRIP/src/main/webapp/UI/admin/admin_player.jsp
- SPORTRIP/src/main/webapp/UI/board/viewPost.jsp
> admin delete

- SPORTRIP/src/main/webapp/UI/assets/css/style.css
- SPORTRIP/src/main/webapp/UI/team/teamPage_stadium.jsp
> update Stadium css

- SPORTRIP/src/main/webapp/UI/admin/admin_board.jsp
- SPORTRIP/src/main/webapp/UI/assets/css/style.css
- SPORTRIP/src/main/webapp/UI/board/board_search.jsp
- SPORTRIP/src/main/webapp/UI/sport/mainPage.jsp
- SPORTRIP/src/main/webapp/UI/team/teamPage_board.jsp
> board search

- SPORTRIP/src/main/webapp/UI/assets/css/style.css
- SPORTRIP/src/main/webapp/UI/team/teamPage_player.jsp
> teampage player

- SPORTRIP/src/main/webapp/UI/admin/admin_addPlayer.jsp
- SPORTRIP/src/main/webapp/UI/admin/admin_updatePlayer.jsp
- SPORTRIP/src/main/webapp/UI/admin/insert_player.jsp
- SPORTRIP/src/main/webapp/UI/admin/update_player.jsp
- SPORTRIP/src/main/webapp/UI/hamburger.jsp
- SPORTRIP/src/main/webapp/UI/sport/sport_main.jsp
- SPORTRIP/src/main/webapp/UI/user/logout.jsp
> add logout

- SPORTRIP/src/main/webapp/UI/sport/sport_header.jsp
- SPORTRIP/src/main/webapp/UI/sport/sport_main.jsp
> header change

- SPORTRIP/src/main/webapp/UI/user/signup.jsp
- SPORTRIP/src/main/webapp/UI/user/signupCheck.jsp
> fix : signup

- SPORTRIP/src/main/webapp/UI/header.jsp
- SPORTRIP/src/main/webapp/UI/sport/matchDate_header.jsp
> logo change

- SPORTRIP/src/main/webapp/UI/assets/css/highlightStyle.css
- SPORTRIP/src/main/webapp/UI/board/viewPost.jsp
- SPORTRIP/src/main/webapp/UI/header.jsp
- SPORTRIP/src/main/webapp/UI/team/teamPage_board.jsp
> board update

- SPORTRIP/src/main/webapp/UI/board/comments.jsp
- SPORTRIP/src/main/webapp/UI/team/teamPage_board.jsp
> content_update

- SPORTRIP/src/main/webapp/UI/md/shoppingPage_paymentDetail.jsp
- SPORTRIP/src/main/webapp/UI/user/myPage.jsp
> fix detail
